### ISSUE TITLE
review coverage

### ISSUE THREAD

**Issue by pkra** [AmerMathSoc/texml-to-html#448]
It looks like there are some unused pieces around (e.g., book-title, meta-*, subj-group - all of which have probably been obsolete since we changed metadata handling).

- [x] 57610a8a86ba8e3409d78fcc0dfbe813f9d68b4d remove book-title.js (obsolete since #254) 
- [x] 2bbc8e05b75b72d3f60968d9c891050b16935cde  remove meta-name.js and meta-value.js (obsolete since #254)
- [x] 9fefa4616d0ebe2068e1dd0d1db56a83fae3ed8b remove subject-group.js and subject.js (obsolete since #254)

**Comment by pkra** [comment]
Coverage is better now thanks to cleaning up unused modules. 

The remaining gaps are fallback values for which we have no tests. We can deal with those in #390.
